data = [
    # 🟩 Multiple Choice (10)
    [
        {
            "question": "Which cooking method involves submerging food in hot fat or oil?",
            "options": ["Boiling", "Baking", "Deep-frying", "Steaming"],
            "answer": "Deep-frying"
        },
        {
            "question": "What is the term for cooking food slowly in liquid at a low temperature?",
            "options": ["Blanching", "Poaching", "Grilling", "Braising"],
            "answer": "Braising"
        },
        {
            "question": "Which tool is commonly used to blend soups and sauces directly in the pot?",
            "options": ["Stand mixer", "Whisk", "Immersion blender", "Food processor"],
            "answer": "Immersion blender"
        },
        {
            "question": "What does 'sauté' mean in cooking?",
            "options": ["Cook in steam", "Cook in oil over high heat", "Grill food", "Boil food quickly"],
            "answer": "Cook in oil over high heat"
        },
        {
            "question": "What is the primary purpose of blanching vegetables?",
            "options": ["To cook them thoroughly", "To soften for roasting", "To loosen skins or preserve color", "To add flavor"],
            "answer": "To loosen skins or preserve color"
        },
        {
            "question": "Which knife cut results in long, thin strips?",
            "options": ["Brunoise", "Julienne", "Dice", "Chop"],
            "answer": "Julienne"
        },
        {
            "question": "What does the term 'al dente' refer to?",
            "options": ["Overcooked", "Raw", "Firm to the bite", "Soft and mushy"],
            "answer": "Firm to the bite"
        },
        {
            "question": "What cooking technique is used to cook meat with dry heat, usually in an oven?",
            "options": ["Braising", "Roasting", "Steaming", "Boiling"],
            "answer": "Roasting"
        },
        {
            "question": "Which technique involves cooking food in vacuum-sealed plastic bags in a water bath?",
            "options": ["Sous-vide", "Steaming", "Baking", "Frying"],
            "answer": "Sous-vide"
        },
        {
            "question": "What does 'deglazing' mean in cooking?",
            "options": ["Adding cream to sauce", "Scraping caramelized bits from pan with liquid", "Marinating meat", "Chopping herbs finely"],
            "answer": "Scraping caramelized bits from pan with liquid"
        },
    ],

    # 🟦 True or False (10)
    [
        {"question": "Boiling and simmering are the same technique.", "answer": "False"},
        {"question": "A mandoline slicer is used to grate cheese.", "answer": "False"},
        {"question": "Braising is a combination of dry and moist heat cooking methods.", "answer": "True"},
        {"question": "Steaming vegetables helps retain more nutrients compared to boiling.", "answer": "True"},
        {"question": "A whisk is best used for cutting meat.", "answer": "False"},
        {"question": "Searing is used to lock in moisture in meat.", "answer": "True"},
        {"question": "Broiling involves cooking food from above using high heat.", "answer": "True"},
        {"question": "Roasting and baking are completely different techniques.", "answer": "False"},
        {"question": "Clarified butter has had the water and milk solids removed.", "answer": "True"},
        {"question": "Flash freezing helps retain the freshness of food.", "answer": "True"},
    ],

    # 🟨 Open Ended (10)
    [
        {"question": "What cooking technique involves browning food quickly in a small amount of fat?", "answer": "Sautéing"},
        {"question": "What term describes the process of soaking meat in a flavorful liquid before cooking?", "answer": "Marinating"},
        {"question": "What is the term for a knife technique that means to cut into very small cubes?", "answer": "Dicing"},
        {"question": "Which technique uses steam generated by boiling water?", "answer": "Steaming"},
        {"question": "What is the process of removing fat from the surface of a liquid?", "answer": "Skimming"},
        {"question": "What does the term 'caramelization' refer to?", "answer": "Browning of sugars"},
        {"question": "What technique involves cooking food in a pan without fat?", "answer": "Dry roasting"},
        {"question": "What is the name for a slow, moist-heat cooking method used for tough cuts of meat?", "answer": "Braising"},
        {"question": "What term is used when food is dipped in boiling water and then placed in ice water?", "answer": "Blanching"},
        {"question": "What is the process of removing bones from meat or fish called?", "answer": "Deboning"},
    ],

    # 🟥 Short Answers (10)
    [
        {"question": "What tool is used to mash potatoes?", "answer": "Masher"},
        {"question": "What is the main tool used to flip pancakes?", "answer": "Spatula"},
        {"question": "What cooking method is used to make French fries?", "answer": "Deep-frying"},
        {"question": "What is used to separate liquid from solid food?", "answer": "Strainer"},
        {"question": "What’s the name of the cooking method that uses radiant heat from above?", "answer": "Broiling"},
        {"question": "Which kitchen tool is used to grate ingredients like cheese?", "answer": "Grater"},
        {"question": "What do you call the method of cooking an egg in water without its shell?", "answer": "Poaching"},
        {"question": "What method is commonly used to preserve meat?", "answer": "Curing"},
        {"question": "What is the name of the traditional Japanese cutting technique used for sushi?", "answer": "Sogigiri"},
        {"question": "What is the French term for a mix of aromatic vegetables used as base?", "answer": "Mirepoix"},
    ]
]

